apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jf3dry6ee-python 
  janus-idp.io/tekton: jf3dry6ee-python
  backstage.io/kubernetes-id: jf3dry6ee-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jf3dry6ee-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  