apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jf3dry6ee-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jf3dry6ee-python 
  name: jf3dry6ee-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jf3dry6ee-python 
